import Config from "tailwindcss";

const theme = {
  colors: {
    background: "var(--color-background)",
    foreground: "var(--color-foreground)",
    primary: "var(--color-primary)",
    "primary-foreground": "var(--color-primary-foreground)",
    secondary: "var(--color-secondary)",
    "secondary-foreground": "var(--color-secondary-foreground)",
    muted: "var(--color-muted)",
    "muted-foreground": "var(--color-muted-foreground)",
    accent: "var(--color-accent)",
    "accent-foreground": "var(--color-accent-foreground)",
    destructive: "var(--color-destructive)",
    "destructive-foreground": "var(--color-destructive-foreground)",
    border: "var(--color-border)",
    input: "var(--color-input)",
    ring: "var(--color-ring)",
    glass: "var(--color-glass)",
    "glass-border": "var(--color-glass-border)",
  },
  fontFamily: {
    sans: ["var(--font-sans)"],
    serif: ["var(--font-serif)"],
    mono: ["var(--font-mono)"],
  },
  fontSize: {
    xs: ["var(--text-xs)", {}],
    sm: ["var(--text-sm)", {}],
    base: ["var(--text-base)", {}],
    lg: ["var(--text-lg)", {}],
    xl: ["var(--text-xl)", {}],
    "2xl": ["var(--text-2xl)", {}],
    "3xl": ["var(--text-3xl)", {}],
    "4xl": ["var(--text-4xl)", {}],
    "5xl": ["var(--text-5xl)", {}],
    "6xl": ["var(--text-6xl)", {}],
  },
  fontWeight: {
    thin: "var(--font-thin)",
    light: "var(--font-light)",
    normal: "var(--font-normal)",
    medium: "var(--font-medium)",
    semibold: "var(--font-semibold)",
    bold: "var(--font-bold)",
    extrabold: "var(--font-extrabold)",
    black: "var(--font-black)",
  },
  lineHeight: {
    none: "var(--leading-none)",
    tight: "var(--leading-tight)",
    snug: "var(--leading-snug)",
    normal: "var(--leading-normal)",
    relaxed: "var(--leading-relaxed)",
    loose: "var(--leading-loose)",
  },
  letterSpacing: {
    tighter: "var(--tracking-tighter)",
    tight: "var(--tracking-tight)",
    normal: "var(--tracking-normal)",
    wide: "var(--tracking-wide)",
    wider: "var(--tracking-wider)",
    widest: "var(--tracking-widest)",
  },
  borderRadius: {
    none: "var(--radius-none)",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    "2xl": "var(--radius-2xl)",
    full: "var(--radius-full)",
  },
  boxShadow: {
    xs: "var(--shadow-xs)",
    sm: "var(--shadow-sm)",
    md: "var(--shadow-md)",
    lg: "var(--shadow-lg)",
    xl: "var(--shadow-xl)",
  },
  zIndex: {
    base: "var(--z-base)",
    dropdown: "var(--z-dropdown)",
    sticky: "var(--z-sticky)",
    overlay: "var(--z-overlay)",
    modal: "var(--z-modal)",
    popover: "var(--z-popover)",
    toast: "var(--z-toast)",
    tooltip: "var(--z-tooltip)",
  },
  transitionDuration: {
    instant: "var(--duration-instant)",
    fast: "var(--duration-fast)",
    normal: "var(--duration-normal)",
    slow: "var(--duration-slow)",
    slower: "var(--duration-slower)",
  },
  transitionTimingFunction: {
    linear: "var(--ease-linear)",
    in: "var(--ease-in)",
    out: "var(--ease-out)",
    "in-out": "var(--ease-in-out)",
    bounce: "var(--ease-bounce)",
  },
  spacing: {
    0: "var(--space-0)",
    1: "var(--space-1)",
    2: "var(--space-2)",
    3: "var(--space-3)",
    4: "var(--space-4)",
    5: "var(--space-5)",
    6: "var(--space-6)",
    8: "var(--space-8)",
    10: "var(--space-10)",
    12: "var(--space-12)",
    16: "var(--space-16)",
    20: "var(--space-20)",
    24: "var(--space-24)",
  },
};

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}"
  ],
  darkMode: "class",
  theme: {
    extend: theme,
  },
  plugins: []
};